export const DESKTOP_MENU_EVENT = 'desktop:menu'
export const DESKTOP_BROWSER_SESSION_EVENT = 'desktop:browser:session-state-updated'
export const DESKTOP_UPDATES_EVENT = 'desktop:updates:state'
export const DESKTOP_DOCUMENT_EXTERNAL_CHANGE_EVENT = 'desktop:document:external-change'

export const IPC_CHANNELS = {
  desktopInfo: 'desktop:get-info',
  readBundledAsset: 'desktop:bundled-asset:read',
  backendStatus: 'desktop:get-backend-status',
  retryBackendStart: 'desktop:retry-backend-start',
  openExternalURL: 'desktop:open-external-url',
  showNotification: 'desktop:show-notification',
  windowAction: 'desktop:window-action',
  openRuntimePath: 'desktop:open-runtime-path',
  bootstrapInitialize: 'desktop:bootstrap:initialize',
  bootstrapCreateAttestation: 'desktop:bootstrap:create-attestation',
  bootstrapStatus: 'desktop:bootstrap:status',
  saveTextFile: 'desktop:file:save-text',
  saveBinaryFile: 'desktop:file:save-binary',
  savePdfFile: 'desktop:file:save-pdf',
  copyDocumentHtml: 'desktop:clipboard:copy-document-html',
  copyImage: 'desktop:clipboard:copy-image',
  readClipboardImage: 'desktop:clipboard:read-image',
  runtimeReferralSummary: 'desktop:runtime:referral-summary',
  submitFeedback: 'desktop:feedback:submit',
  listWorkspaceDocuments: 'desktop:workspace:list-documents',
  readWorkspaceDocument: 'desktop:workspace:read-document',
  statWorkspaceDocument: 'desktop:workspace:stat-document',
  writeWorkspaceDocument: 'desktop:workspace:write-document',
  createWorkspaceDocument: 'desktop:workspace:create-document',
  createWorkspaceFolder: 'desktop:workspace:create-folder',
  moveWorkspaceDocument: 'desktop:workspace:move-document',
  moveWorkspaceFolder: 'desktop:workspace:move-folder',
  deleteWorkspaceDocument: 'desktop:workspace:delete-document',
  deleteWorkspaceFolder: 'desktop:workspace:delete-folder',
  openWorkspaceFile: 'desktop:workspace:open-file',
  saveWorkspaceAsset: 'desktop:workspace:save-asset',
  importWorkspaceFile: 'desktop:workspace:import-file',
  chooseFilesToImport: 'desktop:workspace:choose-files-to-import',
  revealWorkspaceFolder: 'desktop:workspace:reveal-folder',
  chooseWorkspaceFolder: 'desktop:workspace:choose-folder',
  setWorkspaceFolder: 'desktop:workspace:set-folder',
  listVaults: 'desktop:workspace:list-vaults',
  addVault: 'desktop:workspace:add-vault',
  removeVault: 'desktop:workspace:remove-vault',
  renameVault: 'desktop:workspace:rename-vault',
  setActiveVault: 'desktop:workspace:set-active-vault',
  chooseDirectory: 'desktop:workspace:choose-directory',
  openWorkspaceWindow: 'desktop:workspace:open-window',
  chooseAgentAnalysisDirectory: 'desktop:agent:choose-analysis-directory',
  storeSecureValue: 'desktop:secure-store:set',
  readSecureValue: 'desktop:secure-store:get',
  deleteSecureValue: 'desktop:secure-store:delete',
  browserSessionStatus: 'desktop:browser:status',
  ensureBrowserSessionWindow: 'desktop:browser:ensure-window',
  openBrowserSessionHome: 'desktop:browser:open-home',
  hideBrowserSessionPanel: 'desktop:browser:hide-panel',
  goBackBrowserSession: 'desktop:browser:go-back',
  goForwardBrowserSession: 'desktop:browser:go-forward',
  reloadBrowserSession: 'desktop:browser:reload',
  stopBrowserSession: 'desktop:browser:stop',
  setBrowserSessionHostLayout: 'desktop:browser:set-host-layout',
  extractBrowserPageContext: 'desktop:browser:extract-page-context',
  setBrowserSessionTestMock: 'desktop:browser:set-test-mock',
  listBrowserSites: 'desktop:browser:list-sites',
  forgetBrowserSite: 'desktop:browser:forget-site',
  refreshBrowserSiteLoginStatus: 'desktop:browser:refresh-site-login-status',
  updatesGetState: 'desktop:updates:get-state',
  updatesCheck: 'desktop:updates:check',
  updatesDownload: 'desktop:updates:download',
  updatesInstall: 'desktop:updates:install',
  updatesSetBetaChannel: 'desktop:updates:set-beta-channel',
  updatesSetAutoCheck: 'desktop:updates:set-auto-check',
  proxyGet: 'desktop:proxy:get',
  proxySave: 'desktop:proxy:save',
  proxyTest: 'desktop:proxy:test',
  proxyRestartBackend: 'desktop:proxy:restart-backend',
}
